In [1]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("matches.csv")

In [4]:
df

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,1,2026-06-11,Group Stage,A,Mexico,South Africa,2,0,Mexico,No,Tournament opening match at Estadio Azteca
1,2,2026-06-11,Group Stage,A,South Korea,Czechia,2,1,South Korea,No,NaN
2,3,2026-06-12,Group Stage,B,Canada,Bosnia and Herzegovina,1,1,Draw,No,NaN
3,4,2026-06-12,Group Stage,D,United States,Paraguay,4,1,United States,No,NaN
4,5,2026-06-13,Group Stage,B,Switzerland,Qatar,1,1,Draw,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...
87,88,2026-07-03,Round of 32,NaN,Colombia,Ghana,1,0,Colombia,No,NaN
88,89,2026-07-04,Round of 16,NaN,Morocco,Canada,3,0,Morocco,No,Morocco eliminates co-host Canada
89,90,2026-07-04,Round of 16,NaN,France,Paraguay,1,0,France,No,NaN
90,91,2026-07-05,Round of 16,NaN,Norway,Brazil,2,1,Norway,No,NaN
91,92,2026-07-05,Round of 16,NaN,England,Mexico,3,2,England,No,NaN

In [6]:
df.shape

(92, 11)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   match_id              92 non-null     int64
 1   date                  92 non-null     object
 2   stage                 92 non-null     object
 3   group                 72 non-null     object
 4   team_1                92 non-null     object
 5   team_2                92 non-null     object
 6   score_1               92 non-null     int64
 7   score_2               92 non-null     int64
 8   winner                92 non-null     object
 9   decided_by_penalties  92 non-null     object
 10  notes                 6 non-null      object
dtypes: int64(3), object(8)
memory usage: 8.0+ KB

In [8]:
df.describe()

       match_id    score_1    score_2
count  92.00000  92.000000  92.000000
mean   46.50000   2.250000   0.673913
std    26.70206   1.434466   0.712659
min     1.00000   0.000000   0.000000
25%    23.75000   1.000000   0.000000
50%    46.50000   2.000000   1.000000
75%    69.25000   3.000000   1.000000
max    92.00000   7.000000   3.000000

In [16]:
#which country has highest scor
df[df['score_1'] == df['score_1'].max()]['team_1']

8    Germany
Name: team_1, dtype: object

In [17]:
df[df['score_2'] == df['score_2'].max()]['team_2']

66    Austria
Name: team_2, dtype: object

In [18]:
df.columns

Index(['match_id', 'date', 'stage', 'group', 'team_1', 'team_2', 'score_1',
       'score_2', 'winner', 'decided_by_penalties', 'notes'],
      dtype='object')

In [20]:
#which country has low scor
df[df['score_1'] == df['score_1'].min()]['team_1']

14         Spain
33       Ecuador
36       Belgium
46       England
55      Paraguay
62    Cape Verde
68      Colombia
Name: team_1, dtype: object

In [21]:
df[df['score_2'] == df['score_2'].min()]['team_2']

0               South Africa
6                      Haiti
7                    Turkiye
9                    Ecuador
14                Cape Verde
18                   Algeria
23                    Panama
25               South Korea
27                     Qatar
28                  Scotland
29                     Haiti
30                 Australia
31                   Turkiye
33                   Curacao
35                   Tunisia
36                      Iran
38              Saudi Arabia
40                      Iraq
42                   Austria
44                Uzbekistan
45                  DR Congo
46                     Ghana
47                    Panama
48                   Czechia
49               South Korea
52                  Scotland
55                 Australia
57                   Curacao
62              Saudi Arabia
63                   Uruguay
65                      Iraq
68                  Portugal
71                    Panama
72              South Africa
77                    Sweden
78                   Ecuador
81    Bosnia and Herzegovina
82                   Austria
84                   Algeria
87                     Ghana
88                    Canada
89                  Paraguay
Name: team_2, dtype: object

In [22]:
df.head()

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,1,2026-06-11,Group Stage,A,Mexico,South Africa,2,0,Mexico,No,Tournament opening match at Estadio Azteca
1,2,2026-06-11,Group Stage,A,South Korea,Czechia,2,1,South Korea,No,NaN
2,3,2026-06-12,Group Stage,B,Canada,Bosnia and Herzegovina,1,1,Draw,No,NaN
3,4,2026-06-12,Group Stage,D,United States,Paraguay,4,1,United States,No,NaN
4,5,2026-06-13,Group Stage,B,Switzerland,Qatar,1,1,Draw,No,NaN

In [23]:
df.tail()

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
87,88,2026-07-03,Round of 32,NaN,Colombia,Ghana,1,0,Colombia,No,NaN
88,89,2026-07-04,Round of 16,NaN,Morocco,Canada,3,0,Morocco,No,Morocco eliminates co-host Canada
89,90,2026-07-04,Round of 16,NaN,France,Paraguay,1,0,France,No,NaN
90,91,2026-07-05,Round of 16,NaN,Norway,Brazil,2,1,Norway,No,NaN
91,92,2026-07-05,Round of 16,NaN,England,Mexico,3,2,England,No,NaN

In [25]:
#total teams in fifa 
df['team_1'].value_counts().count()
df['team_2'].value_counts().count()

np.int64(41)

In [26]:
df.isna()

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
87,False,False,False,True,False,False,False,False,False,False,True
88,False,False,False,True,False,False,False,False,False,False,False
89,False,False,False,True,False,False,False,False,False,False,True
90,False,False,False,True,False,False,False,False,False,False,True
91,False,False,False,True,False,False,False,False,False,False,True

In [27]:
df.isna().sum()

match_id                 0
date                     0
stage                    0
group                   20
team_1                   0
team_2                   0
score_1                  0
score_2                  0
winner                   0
decided_by_penalties     0
notes                   86
dtype: int64

In [28]:
df.isna().any()

match_id                False
date                    False
stage                   False
group                    True
team_1                  False
team_2                  False
score_1                 False
score_2                 False
winner                  False
decided_by_penalties    False
notes                    True
dtype: bool

In [29]:
df

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,1,2026-06-11,Group Stage,A,Mexico,South Africa,2,0,Mexico,No,Tournament opening match at Estadio Azteca
1,2,2026-06-11,Group Stage,A,South Korea,Czechia,2,1,South Korea,No,NaN
2,3,2026-06-12,Group Stage,B,Canada,Bosnia and Herzegovina,1,1,Draw,No,NaN
3,4,2026-06-12,Group Stage,D,United States,Paraguay,4,1,United States,No,NaN
4,5,2026-06-13,Group Stage,B,Switzerland,Qatar,1,1,Draw,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...
87,88,2026-07-03,Round of 32,NaN,Colombia,Ghana,1,0,Colombia,No,NaN
88,89,2026-07-04,Round of 16,NaN,Morocco,Canada,3,0,Morocco,No,Morocco eliminates co-host Canada
89,90,2026-07-04,Round of 16,NaN,France,Paraguay,1,0,France,No,NaN
90,91,2026-07-05,Round of 16,NaN,Norway,Brazil,2,1,Norway,No,NaN
91,92,2026-07-05,Round of 16,NaN,England,Mexico,3,2,England,No,NaN

In [30]:
df.dropna()

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,1,2026-06-11,Group Stage,A,Mexico,South Africa,2,0,Mexico,No,Tournament opening match at Estadio Azteca
42,43,2026-06-22,Group Stage,J,Argentina,Austria,2,0,Argentina,No,Messi broke World Cup all-time goalscoring rec...

In [31]:
df

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,1,2026-06-11,Group Stage,A,Mexico,South Africa,2,0,Mexico,No,Tournament opening match at Estadio Azteca
1,2,2026-06-11,Group Stage,A,South Korea,Czechia,2,1,South Korea,No,NaN
2,3,2026-06-12,Group Stage,B,Canada,Bosnia and Herzegovina,1,1,Draw,No,NaN
3,4,2026-06-12,Group Stage,D,United States,Paraguay,4,1,United States,No,NaN
4,5,2026-06-13,Group Stage,B,Switzerland,Qatar,1,1,Draw,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...
87,88,2026-07-03,Round of 32,NaN,Colombia,Ghana,1,0,Colombia,No,NaN
88,89,2026-07-04,Round of 16,NaN,Morocco,Canada,3,0,Morocco,No,Morocco eliminates co-host Canada
89,90,2026-07-04,Round of 16,NaN,France,Paraguay,1,0,France,No,NaN
90,91,2026-07-05,Round of 16,NaN,Norway,Brazil,2,1,Norway,No,NaN
91,92,2026-07-05,Round of 16,NaN,England,Mexico,3,2,England,No,NaN

In [34]:
df.dropna(thresh=1)

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,1,2026-06-11,Group Stage,A,Mexico,South Africa,2,0,Mexico,No,Tournament opening match at Estadio Azteca
1,2,2026-06-11,Group Stage,A,South Korea,Czechia,2,1,South Korea,No,NaN
2,3,2026-06-12,Group Stage,B,Canada,Bosnia and Herzegovina,1,1,Draw,No,NaN
3,4,2026-06-12,Group Stage,D,United States,Paraguay,4,1,United States,No,NaN
4,5,2026-06-13,Group Stage,B,Switzerland,Qatar,1,1,Draw,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...
87,88,2026-07-03,Round of 32,NaN,Colombia,Ghana,1,0,Colombia,No,NaN
88,89,2026-07-04,Round of 16,NaN,Morocco,Canada,3,0,Morocco,No,Morocco eliminates co-host Canada
89,90,2026-07-04,Round of 16,NaN,France,Paraguay,1,0,France,No,NaN
90,91,2026-07-05,Round of 16,NaN,Norway,Brazil,2,1,Norway,No,NaN
91,92,2026-07-05,Round of 16,NaN,England,Mexico,3,2,England,No,NaN

In [35]:
df.fillna(0)

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,1,2026-06-11,Group Stage,A,Mexico,South Africa,2,0,Mexico,No,Tournament opening match at Estadio Azteca
1,2,2026-06-11,Group Stage,A,South Korea,Czechia,2,1,South Korea,No,0
2,3,2026-06-12,Group Stage,B,Canada,Bosnia and Herzegovina,1,1,Draw,No,0
3,4,2026-06-12,Group Stage,D,United States,Paraguay,4,1,United States,No,0
4,5,2026-06-13,Group Stage,B,Switzerland,Qatar,1,1,Draw,No,0
...,...,...,...,...,...,...,...,...,...,...,...
87,88,2026-07-03,Round of 32,0,Colombia,Ghana,1,0,Colombia,No,0
88,89,2026-07-04,Round of 16,0,Morocco,Canada,3,0,Morocco,No,Morocco eliminates co-host Canada
89,90,2026-07-04,Round of 16,0,France,Paraguay,1,0,France,No,0
90,91,2026-07-05,Round of 16,0,Norway,Brazil,2,1,Norway,No,0
91,92,2026-07-05,Round of 16,0,England,Mexico,3,2,England,No,0

In [37]:
df.head()

,match_id,date,stage,group,team_1,team_2,score_1,score_2,winner,decided_by_penalties,notes
0,1,2026-06-11,Group Stage,A,Mexico,South Africa,2,0,Mexico,No,Tournament opening match at Estadio Azteca
1,2,2026-06-11,Group Stage,A,South Korea,Czechia,2,1,South Korea,No,NaN
2,3,2026-06-12,Group Stage,B,Canada,Bosnia and Herzegovina,1,1,Draw,No,NaN
3,4,2026-06-12,Group Stage,D,United States,Paraguay,4,1,United States,No,NaN
4,5,2026-06-13,Group Stage,B,Switzerland,Qatar,1,1,Draw,No,NaN

In [38]:
table = df.groupby('team_1')['score_1'].sum()

In [39]:
table

team_1
Algeria                    5
Argentina                 11
Australia                  2
Austria                    3
Belgium                    9
Bosnia and Herzegovina     3
Brazil                     9
Canada                     8
Cape Verde                 0
Colombia                   5
Croatia                    3
Czechia                    1
DR Congo                   3
Ecuador                    2
Egypt                      5
England                   11
France                    14
Germany                    9
Ghana                      1
Iran                       2
Ivory Coast                3
Japan                      5
Mexico                     8
Morocco                    9
Netherlands               10
Norway                    11
Paraguay                   2
Portugal                   8
Saudi Arabia               1
Scotland                   1
Senegal                    5
South Africa               1
South Korea                2
Spain                      8
Sweden                     5
Switzerland                9
Turkiye                    3
United States              8
Uruguay                    2
Name: score_1, dtype: int64

In [41]:
table2 = df.groupby('team_2')['score_2'].sum()

In [42]:
table2

team_2
Algeria                   0
Australia                 1
Austria                   3
Bosnia and Herzegovina    2
Brazil                    1
Canada                    1
Cape Verde                4
Croatia                   3
Curacao                   1
Czechia                   1
DR Congo                  2
Ecuador                   0
Egypt                     1
Germany                   2
Ghana                     1
Haiti                     2
Iran                      1
Iraq                      1
Ivory Coast               2
Japan                     3
Jordan                    3
Mexico                    2
Morocco                   1
Netherlands               1
New Zealand               4
Norway                    1
Panama                    0
Paraguay                  1
Portugal                  0
Qatar                     2
Saudi Arabia              0
Scotland                  0
Senegal                   5
South Africa              1
South Korea               0
Sweden                    2
Tunisia                   2
Turkiye                   0
United States             2
Uruguay                   1
Uzbekistan                2
Name: score_2, dtype: int64